#+TITLE: A competência do tribunal arbitral: indicações bibligráficas e jurisprudenciais
#+AUTHOR: João Gomes de Almeida
#+LANGUAGE: pt
#+OPTIONS: date:nil toc:nil
#+LATEX_CLASS: koma-article
#+LATEX_COMPILER: xelatex

* Bibliografia

As indicações bibliográficas que se seguem não têm qualquer pretensão de exaustividade e visam apenas constituir um ponto de partida para quem pretenda aprofundar o estudo do tema da competência do tribunal arbitral. Deste modo privilegiou-se, em regra, as publicações mais recentes e ou que sejam mais facilmente acessíveis pelos participantes do Curso de Pós-Graduação. Agrupa-se a bibliografia em nacional e estrangeira e ordena-se a mesma pela data de publicação e ordem alfabética do apelido do (primeiro) autor. A bibliografia estrangeira encontra-se disponível na base de dados [[https://www.kluwerarbitration.com/][Kluwer Arbitration]] e pode ser acedida na Biblioteca da FDUL.

** Nacional

- Oliveira, Elsa Dias. /Arbitragem Voluntária: Uma Introdução/. Coimbra: Almedina, 2020, pp. 73-84.
- Pires, Catarina Monteiro, e Rui Pereira Dias, eds. /Manual de Arbitragem Internacional Lusófona/. Vol. I. Coimbra: Almedina, 2020, pp. 73-79.
- Monteiro, António Pedro Pinto, Artur Flamínio da Silva, e Daniela Mirante. /Manual de arbitragem/. Coimbra: Almedina, 2019, pp. 187-191.
- Vicente, Dário Moura, André Navarro de Noronha, Armindo Ribeiro Mendes, José Miguel Júdice, José Robin de Andrade, Miguel de Almada, Nuno Ferreira Lousa, /et al/. /Lei da arbitragem voluntária: anotada/. 4.ª ed. Coimbra: Almedina, 2019, pp. 87-93.
- Cordeiro, António Manuel da Rocha e Menezes. /Tratado da arbitragem - Comentário à Lei 63/2011, de 14 de dezembro/. Coimbra: Almedina, 2015, pp. 189-213.
- Caramelo, António Sampaio. «A competência da competência e a autonomia doTribunal arbitral na Lei de arbitragem portuguesa». /Revista del Club Español del Arbitraje/, n. 19 (2014): 19–42 (disponível na Kluwer Arbitration).

** Estrangeira

- Born, Gary. /International Commercial Arbitration/, 3.ª ed. Alphen aan den Rijn: Wolters Kluwer, 2021, pp. 1139-1348.
- Binder, Peter. /International commercial arbitration and mediation in UNCITRAL model law jurisdictions/, 4.ª ed. Alphen aan den Rijn, The Netherlands: Kluwer Law International B. V, 2019, pp. 251-276.
- Holtzmann, Howard M., Joseph E. Neuhaus, Edda Kristjánsdóttir, e Thomas W. Walsh. /A guide to the 2006 amendments to the UNCITRAL model law on international commercial arbitration: legislative history and commentary/. Alphen aan den Rijn, the Netherlands: Wolters Kluwer, Law & Business, 2015, pp. 478-528.
- Huber, Peter, e Ivo Bach. /Arbitration in Germany: the model law in practice/, editado por Karl-Heinz Böckstiegel, Stefan Kröll, e Patricia Nacimiento, 2.ª ed. Alphen aan den Rijn, The Netherlands: Kluwer Law International, 2015, pp. 215-225.
- Redfern, Alan, Nigel Blackaby, Constatntine Partasides, e Martin Hunter.  /Redfern and Hunter on International Arbitration/, 6.ª ed. Oxford: Oxford University Press, 2015, pp. 305-352 (disponível na Kluwer Arbitration).
- Lew, Julian D. M., Loukas A. Mistelis, Stefan Kröll, e Stefan M. Kröll.  /Comparative International Commercial Arbitration/. The Hague [u.a]: Kluwer Law International, 2003, pp. 329–354.
- Fouchard, Philippe, Emmanuel Gaillard, e Berthold Goldman. /International Commercial Arbitration/. The Hague: Kluwer Law International, 1999, pp. 213-214 e pp. 395-401.

* Jurisprudência

Neste ponto, optou-se por indicar alguns dos acórdãos mais recentes proferidos pelo Supremo Tribunal de Justiça, todos disponíveis na base de dados da [[http://www.dgsi.pt/][DGSI]], com exceção do de 23 de abril de 2020, que se encontra disponível na base de dados do [[https://jurisprudencia.csm.org.pt/][Conselho Superior da Magistratura]].

- Acórdão do Supremo Tribunal de Justiça de 23 de março de 2021, proc. 38/18.1T8VRL-A.E1.S1 (relator Pedro de Lima Gonçalves).
- Acórdão do Supremo Tribunal de Justiça de 23 de abril de 2020, proc. 1556/18.7T8PVZ.P1.S1 (relator Rosa Tching).
- Acórdão do Supremo Tribunal de Justiça de 20 de março de 2018, proc. 1149/14.8T8LRS.L1.S1 (relator Henrique Araújo).
- Acórdão do Supremo Tribunal de Justiça de 21 de junho de 2016, proc. 301/14.0TVLSB.L1.S1 (relator Fernandes do Vale).
- Acórdão do Supremo Tribunal de Justiça de 12 de maio de 2016, proc. 710/14.5TVLSB-A.L1.S1 (relator Oliveira Vasconcelos).
- Acórdão do Supremo Tribunal de Justiça de 2 de junho de 2015, proc. 1279/14.6TVLSB.S1 (relator Garcia Calejo).
